# Generated by Django 5.2.17 on 2026-08-12 17:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('round_number', models.PositiveSmallIntegerField(default=1)),
                ('interview_type', models.CharField(choices=[('phone', 'Phone Screening'), ('video', 'Video Call'), ('technical', 'Technical Interview'), ('hr', 'HR / Culture'), ('system_design', 'System Design'), ('coding', 'Live Coding / Pair Programming'), ('behavioral', 'Behavioral'), ('onsite', 'On-site'), ('other', 'Other')], default='technical', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=16)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=45)),
                ('interviewer_name', models.CharField(blank=True, max_length=160)),
                ('interviewer_email', models.EmailField(blank=True, max_length=254)),
                ('meeting_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('notes', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('scheduled_at',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('reminder', 'Reminder Alert'), ('interview', 'Upcoming Interview'), ('status_update', 'Status Update'), ('system', 'System Notice')], default='reminder', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('related_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='applications.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('linkedin_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('last_contact_date', models.DateField(blank=True, null=True)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiters', to='applications.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('phone_call', 'Phone Call'), ('linkedin', 'LinkedIn Message'), ('whatsapp', 'WhatsApp'), ('video_call', 'Video Call'), ('in_person', 'In Person'), ('other', 'Other')], default='email', max_length=20)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], default='outbound', max_length=10)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('contact_date', models.DateTimeField()),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='applications.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to=settings.AUTH_USER_MODEL)),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='applications.recruiter')),
            ],
            options={
                'ordering': ('-contact_date',),
            },
        ),
        migrations.AddField(
            model_name='application',
            name='primary_recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='applications.recruiter'),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('reminder_type', models.CharField(choices=[('follow_up', 'Follow-up'), ('interview', 'Interview Preparation'), ('deadline', 'Application Deadline'), ('custom', 'Custom Reminder')], default='follow_up', max_length=16)),
                ('due_at', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='applications.application')),
                ('interview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='applications.interview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('due_at',),
            },
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['user', 'scheduled_at'], name='application_user_id_4bd1a8_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['application', 'scheduled_at'], name='application_applica_9ace65_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='application_user_id_31a876_idx'),
        ),
        migrations.AddIndex(
            model_name='recruiter',
            index=models.Index(fields=['user', 'name'], name='application_user_id_1b1883_idx'),
        ),
        migrations.AddIndex(
            model_name='recruiter',
            index=models.Index(fields=['user', 'company'], name='application_user_id_7ce6e4_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['user', 'application', '-contact_date'], name='application_user_id_c0c309_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['user', 'follow_up_date'], name='application_user_id_c0170d_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['user', 'is_completed', 'due_at'], name='application_user_id_c449c6_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['application', 'due_at'], name='application_applica_3cd1cb_idx'),
        ),
    ]
