# Generated by Django 5.2.17 on 2026-08-12 18:51

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_interview_notification_recruiter_communication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('resume', 'Resume / CV'), ('cover_letter', 'Cover Letter'), ('portfolio', 'Portfolio / Work Sample'), ('certificate', 'Certificate / Diploma'), ('other', 'Other Document')], default='resume', max_length=32)),
                ('file', models.FileField(upload_to=apps.documents.models.user_document_directory_path)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('is_primary', models.BooleanField(default=False, help_text='Designates this as the primary active resume for general applications.')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('parsed_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='applications.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_primary', '-created_at'),
                'indexes': [models.Index(fields=['user', 'doc_type'], name='documents_d_user_id_b54e08_idx'), models.Index(fields=['user', 'is_primary'], name='documents_d_user_id_0ef9e3_idx')],
            },
        ),
    ]
